services:
  shop_catalogue-db:
    image: postgres:15-alpine
    container_name: shop_catalogue-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop_catalogue_db
      POSTGRES_USER: shop_catalogue_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - shop_catalogue-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop_catalogue_user -d shop_catalogue_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  shop_catalogue-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop_catalogue-service:latest
    container_name: shop_catalogue-service
    depends_on:
      shop_catalogue-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shop_catalogue-db:5432/shop_catalogue_db
      SPRING_DATASOURCE_USERNAME: shop_catalogue_user
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  shop_catalogue-db-data:
