eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

wallet:
  service:
    url: ${WALLET_SERVICE_URL:http://wallet-service:8092}
